// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import ToggleModalController from './toggle_modal_controller';
application.register('toggle-modal', ToggleModalController)
